name: Nightly Build

env:
  YARN_INSTALL_NOPT: yarn add --ignore-platform --ignore-optional

on:
  push:
    branches:
      - test_build
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install build tools (on Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update &&
          sudo apt-get install --no-install-recommends -y libarchive-tools &&
          sudo apt-get install --no-install-recommends -y libopenjp2-tools

      - id: get_unm_version
        name: Get the installed UNM version
        run: |
          yarn --ignore-optional
          unm_version=$(node -e "console.log(require('./node_modules/@unblockneteasemusic/rust-napi/package.json').version)")
          echo "::set-output name=unmver::${unm_version}"
        shell: bash

      - name: Install UNM dependencies for Windows
        if: runner.os == 'Windows'
        run: |
          ${{ env.YARN_INSTALL_NOPT }} \
            @unblockneteasemusic/rust-napi-win32-x64-msvc@${{steps.get_unm_version.outputs.unmver}}
        shell: bash

      - name: Install UNM dependencies for macOS
        if: runner.os == 'macOS'
        run: |
          ${{ env.YARN_INSTALL_NOPT }} \
            @unblockneteasemusic/rust-napi-darwin-x64@${{steps.get_unm_version.outputs.unmver}} \
            @unblockneteasemusic/rust-napi-darwin-arm64@${{steps.get_unm_version.outputs.unmver}} \
            dmg-license
        shell: bash

      - name: Install UNM dependencies for Linux
        if: runner.os == 'Linux'
        run: |
          ${{ env.YARN_INSTALL_NOPT }} \
            @unblockneteasemusic/rust-napi-linux-x64-gnu@${{steps.get_unm_version.outputs.unmver}}
        shell: bash

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        env:
          VUE_APP_NETEASE_API_URL: /api
          VUE_APP_ELECTRON_API_URL: /api
          VUE_APP_ELECTRON_API_URL_DEV: http://127.0.0.1:10754
          VUE_APP_LASTFM_API_KEY: 09c55292403d961aa517ff7f5e8a3d9c
          VUE_APP_LASTFM_API_SHARED_SECRET: 307c9fda32b3904e53654baff215cb67
          NIGHTLY_BUILD: 'true'
        with:
          github_token: ${{ secrets.github_token }}
          release: false
          use_vue_cli: true

      - uses: actions/upload-artifact@v4
        if: runner.os == 'Linux'
        with:
          name: YesPlayMusic-nightly-linux
          path: dist_electron/*.AppImage
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: runner.os == 'Windows'
        with:
          name: YesPlayMusic-nightly-win
          path: dist_electron/*Setup*.exe
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: YesPlayMusic-nightly-mac
          path: dist_electron/*-universal.dmg
          if-no-files-found: ignore
